enabled: true
container:
  image: docker.io/linuxserver/sonarr
  nodeSelector: {}
  port: 8989
service:
  type: ClusterIP
  port: 8989
  nodePort:
  extraLBService: false
  extraLBAnnotations: {}
  # Defines an additional LB service, requires cloud provider service or MetalLB
ingress:
  enabled: true
  annotations: {}
  path: /sonarr
  tls:
    enabled: false
    secretName: ""
resources: {}
volume: {}
  #name: pvc-sonarr-config
  #storageClassName: longhorn
  #annotations:
  #  my-annotation/test: my-value
  #labels:
  #  my-label/test: my-other-value
  #accessModes: ReadWriteOnce
  #storage: 5Gi
  #selector: {}
