enabled: true
claim: "CHANGEME"
replicaCount: 1
container:
  image: docker.io/linuxserver/plex
  nodeSelector: {}
  port: 32400
service:
  type: ClusterIP
  port: 32400
  nodePort:
  # Defines an additional LB service, requires cloud provider service or MetalLB
  extraLBService: false
  extraLBAnnotations: {}
ingress:
  enabled: true
  annotations: {}
  tls:
    enabled: false
    secretName: ""
resources: {}
volume: {}
storage:
  customVolume: false  #set to true if not using a PVC (must provide volume below)
  pvcName: mediaserver-pvc
  accessMode: ""
  size: 5Gi
  pvcStorageClass: ""
  subPaths:
    tv: media/tv
    movies: media/movies
    downloads: downloads
    transmission: transmission
    sabnzbd: sabnzbd
    config: config
  volumes: {}
nodeSelector: {}
