apiVersion: kubealex.com/v1
kind: K8SMediaserver
metadata:
  name: k8smediaserver-sample
spec:
  general:
    ingress_host: media.10.100.102.50.nip.io
    plex_ingress_host: plex.10.100.102.50.nip.io
    image_tag: latest
    puid: 1000
    pgid: 1000
    storage:
      pvcName: mediaserver-pvc
      size: 80Gi
      pvcStorageClass: "longhorn"
      subPaths:
        tv: media/tv
        movies: media/movies
        downloads: downloads
        transmission: transmission
        sabnzbd: sabnzbd
        config: config
  sonarr:
    enabled: true
    container:
      nodeSelector: {}
      port: 8989
    service:
      type: ClusterIP
      port: 8989
      nodePort:
      extraLBService: false
    ingress:
      enabled: true
      annotations: {}
      path: /sonarr
      tls:
        enabled: false
        secretName: ""
    resources: {}

  radarr:
    enabled: true
    container:
      nodeSelector: {}
      port: 7878
    service:
      type: ClusterIP
      port: 7878
      nodePort:
      extraLBService: false
    ingress:
      enabled: true
      annotations: {}
      path: /radarr
      tls:
        enabled: false
        secretName: ""
    resources: {}

  jackett:
    enabled: true
    container:
      nodeSelector: {}
      port: 9117
    service:
      type: ClusterIP
      port: 9117
      nodePort:
      extraLBService: false
    ingress:
      enabled: true
      annotations: {}
      path: /jackett
      tls:
        enabled: false
        secretName: ""
    resources: {}

  transmission:
    enabled: true
    container:
      nodeSelector: {}
      port:
        utp: 9091
        peer: 51413
    service:
      utp:
        type: ClusterIP
        port: 9091
        nodePort:
        extraLBService: false
      peer:
        type: ClusterIP
        port: 51413
        nodePort:
        nodePortUDP:
        extraLBService: false
    ingress:
      enabled: true
      annotations: {}
      path: /transmission
      tls:
        enabled: false
        secretName: ""
    config:
      auth:
        enabled: false
        username: ""
        password: ""
    resources: {}

  sabnzbd:
    enabled: true
    container:
      nodeSelector: {}
      port:
        http: 8080
        https: 9090
    service:
      http:
        type: ClusterIP
        port: 8080
        nodePort:
        extraLBService: false
      https:
        type: ClusterIP
        port: 9090
        nodePort:
        extraLBService: false
    ingress:
      enabled: true
      annotations: {}
      path: /sabnzbd
      tls:
        enabled: false
        secretName: ""
    resources: {}

  plex:
    enabled: true
    claim: "CHANGEME"
    replicaCount: 1
    container:
      nodeSelector: {}
      port: 32400
    service:
      type: ClusterIP
      port: 32400
      nodePort:
      extraLBService: false
    ingress:
      enabled: true
      annotations: {}
      tls:
        enabled: false
        secretName: ""
    resources: {}
