### CONFIGMAP
## INIT-CONTAINER
apiVersion: v1
data:
  config.xml: |
    <Config>
      <UrlBase>{{ .Values.ingress.path }}</UrlBase>
    </Config>
  init-sonarr.sh: |
    #!/bin/bash
    echo "### Initializing config ###"
    if [ ! -f /sonarr-config/config.xml ]; then
      cp -n /init-sonarr/config.xml /sonarr-config/config.xml
      echo "### No configuration found, intialized with default settings ###"
    fi
kind: ConfigMap
metadata:
  name: init-sonarr-cm
---
## APPLICATION
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarr-config
data:
  PGID: "{{ .Values.global.pgid }}"
  PUID: "{{ .Values.global.puid }}"
---
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-mediaserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-mediaserver.selectorLabels" . | nindent 8 }}
        app: sonarr
    spec:
      initContainers:
        - name: config-sonarr
          image: docker.io/ubuntu:groovy
          command: ["/init-sonarr/init-sonarr.sh"]
          volumeMounts:
            - mountPath: /init-sonarr
              name: init-files-sonarr
          {{- if .Values.volume }}
            - name: {{ .Values.volume.name }}
              mountPath: /sonarr-config
          {{- else }}
            - name: mediaserver-volume
              mountPath: /sonarr-config
              subPath: "{{ .Values.global.storage.subPaths.config }}/sonarr"
          {{- end }}
          securityContext:
            runAsUser: {{ .Values.global.puid }}
            runAsGroup: {{ .Values.global.pgid }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: sonarr-config
          image: "{{ .Values.container.image }}:{{ .Values.container.tag | default .Values.global.image_tag }}"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: "/{{ .Values.ingress.path }}/ping"
              port: {{ .Values.container.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          ports:
            - name: sonarr-port
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          volumeMounts:
          {{- if .Values.volume }}
            - name: {{ .Values.volume.name }}
              mountPath: /config
          {{- else }}
            - name: mediaserver-volume
              mountPath: "/config"
              subPath: "{{ .Values.global.storage.subPaths.config }}/sonarr"
          {{- end }}
            - name: mediaserver-volume
              mountPath: "/downloads"
              subPath: "{{ .Values.global.storage.subPaths.downloads }}"
            - name: mediaserver-volume
              mountPath: "/tv"
              subPath: "{{ .Values.global.storage.subPaths.tv }}"
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if not .Values.global.storage.customVolume }}
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.global.storage.pvcName }}
        {{- else }}
        - name: mediaserver-volume
          {{- toYaml .Values.global.storage.volumes | nindent 10 }}
        {{- end }}
        {{- if .Values.volume }}
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volume.name }}
        {{- end }}
        - name: init-files-sonarr
          configMap:
            defaultMode: 493
            name: init-sonarr-cm
      {{- with merge .Values.container.nodeSelector .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.global.podDistribution "cluster" }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
            weight: 100
      {{- else if eq .Values.global.podDistribution "spread" }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: "ScheduleAnyway"
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: {{ .Release.Name }}
      {{- end }}
---
### SERVICES
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
{{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
{{ end }}
      name: sonarr-port
  selector:
    app: sonarr
---
{{ if .Values.service.extraLBService }}
apiVersion: v1
kind: Service
metadata:
  name: sonarr-lb
  {{- with .Values.service.extraLBAnnotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
      name: sonarr-port
  selector:
    app: sonarr
{{ end }}
---
### INGRESS
{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.global.ingress_host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{ end }}
  ingressClassName: {{ .Values.global.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.global.ingress_host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: {{ .Values.service.port }}
{{ end }}
