enabled: true
container:
  image: docker.io/linuxserver/transmission
  nodeSelector: {}
  port:
    utp: 9091
    peer: 51413
service:
  utp:
    type: ClusterIP
    port: 9091
    # if type is NodePort, nodePort must be set
    nodePort:
    # Defines an additional LB service, requires cloud provider service or MetalLB
    extraLBService: false
    extraLBAnnotations: {}
  peer:
    type: ClusterIP
    port: 51413
    # if type is NodePort, nodePort and nodePortUDP must be set
    nodePort:
    nodePortUDP:
    # Defines an additional LB service, requires cloud provider service or MetalLB
    extraLBService: false
    extraLBAnnotations: {}
ingress:
  enabled: true
  annotations: {}
  path: /transmission
  tls:
    enabled: false
    secretName: ""
config:
  auth:
    enabled: false
    username: ""
    password: ""
resources: {}
volume: {}
#  name: pvc-transmission-config
#  storageClassName: longhorn
#  annotations: {}
#  labels: {}
#  accessModes: ReadWriteOnce
#  storage: 5Gi
#  selector: {}
