apiVersion: charts.kubealex.com/v1
kind: K8SMediaserver
metadata:
  name: k8smediaserver-sample
spec:
  # Default values copied from <project_dir>/helm-charts/k8s-mediaserver/values.yaml
  general:
    image_tag: latest
    ingress:
      ingressClassName: ""
    ingress_host: k8s-mediaserver.k8s.test
    pgid: 1000
    plex_ingress_host: k8s-plex.k8s.test
    puid: 1000
    storage:
      customVolume: false
      pvcName: mediaserver-pvc
      pvcStorageClass: []
      size: 5Gi
      subPaths:
        config: config
        downloads: downloads
        movies: media/movies
        sabnzbd: sabnzbd
        transmission: transmission
        tv: media/tv
      volumes: {}
  jackett:
    container:
      nodeSelector: {}
      port: 9117
    enabled: true
    ingress:
      annotations: {}
      enabled: true
      path: /jackett
      tls:
        enabled: false
        secretName: ""
    resources: {}
    service:
      extraLBService: false
      nodePort: null
      port: 9117
      type: ClusterIP
  plex:
    claim: CHANGEME
    container:
      nodeSelector: {}
      port: 32400
    enabled: true
    ingress:
      annotations: {}
      enabled: true
      tls:
        enabled: false
        secretName: ""
    replicaCount: 1
    resources: {}
    service:
      extraLBService: false
      nodePort: null
      port: 32400
      type: ClusterIP
  radarr:
    container:
      nodeSelector: {}
      port: 7878
    enabled: true
    ingress:
      annotations: {}
      enabled: true
      path: /radarr
      tls:
        enabled: false
        secretName: ""
    resources: {}
    service:
      extraLBService: false
      nodePort: null
      port: 7878
      type: ClusterIP
  sabnzbd:
    container:
      nodeSelector: {}
      port:
        http: 8080
        https: 9090
    enabled: true
    ingress:
      annotations: {}
      enabled: true
      path: /sabnzbd
      tls:
        enabled: false
        secretName: ""
    resources: {}
    service:
      http:
        extraLBService: false
        nodePort: null
        port: 8080
        type: ClusterIP
      https:
        extraLBService: false
        nodePort: null
        port: 9090
        type: ClusterIP
  sonarr:
    container:
      nodeSelector: {}
      port: 8989
    enabled: true
    ingress:
      annotations: {}
      enabled: true
      path: /sonarr
      tls:
        enabled: false
        secretName: ""
    resources: {}
    service:
      extraLBService: false
      nodePort: null
      port: 8989
      type: ClusterIP
  transmission:
    config:
      auth:
        enabled: false
        password: ""
        username: ""
    container:
      nodeSelector: {}
      port:
        peer: 51413
        utp: 9091
    enabled: true
    ingress:
      annotations: {}
      enabled: true
      path: /transmission
      tls:
        enabled: false
        secretName: ""
    resources: {}
    service:
      peer:
        extraLBService: false
        nodePort: null
        nodePortUDP: null
        port: 51413
        type: ClusterIP
      utp:
        extraLBService: false
        nodePort: null
        port: 9091
        type: ClusterIP
  
  
