apiVersion: charts.kubealex.com/v1
kind: K8SMediaserver
metadata:
  name: k8smediaserver-sample
spec:
  # Default values copied from <project_dir>/helm-charts/k8s-mediaserver/values.yaml
  general:
    ingress:
      ingressClassName: ""
    ingress_host: k8s-mediaserver.k8s.test
    nodeSelector: {}
    plex_ingress_host: k8s-plex.k8s.test
    image_tag: latest
    podDistribution: cluster
    # UID to run the process with
    puid: 1000
    # GID to run the process with
    pgid: 1000
    # Persistent storage selections and pathing
    storage:
      customVolume: false  # set to true if not using a PVC (must provide volume below)
      pvcName: mediaserver-pvc
      size: 5Gi
      pvcStorageClass: ""
      subPaths:
        config: config
        downloads: downloads
        movies: media/movies
        sabnzbd: sabnzbd
        transmission: transmission
        tv: media/tv
      volumes: {}
  jackett:
    container:
      image: docker.io/linuxserver/jackett
      nodeSelector: {}
      port: 9117
    enabled: true
    ingress:
      annotations: {}
      enabled: true
      path: /jackett
      tls:
        enabled: false
        secretName: ""
    resources: {}
    service:
      extraLBAnnotations: {}
      extraLBService: false
      nodePort: null
      port: 9117
      type: ClusterIP
    volume: {}
  plex:
    claim: CHANGEME
    container:
      image: docker.io/linuxserver/plex
      nodeSelector: {}
      port: 32400
    enabled: true
    ingress:
      annotations: {}
      enabled: true
      tls:
        enabled: false
        secretName: ""
    replicaCount: 1
    resources: {}
    service:
      extraLBAnnotations: {}
      extraLBService: false
      nodePort: null
      port: 32400
      type: ClusterIP
    volume: {}
  prowlarr:
    container:
      image: docker.io/linuxserver/prowlarr
      nodeSelector: {}
      port: 9696
      tag: develop
    enabled: true
    ingress:
      annotations: {}
      enabled: true
      path: /prowlarr
      tls:
        enabled: false
        secretName: ""
    resources: {}
    service:
      extraLBAnnotations: {}
      extraLBService: false
      nodePort: null
      port: 9696
      type: ClusterIP
    volume: {}
  radarr:
    container:
      image: docker.io/linuxserver/radarr
      nodeSelector: {}
      port: 7878
    enabled: true
    ingress:
      annotations: {}
      enabled: true
      path: /radarr
      tls:
        enabled: false
        secretName: ""
    resources: {}
    service:
      extraLBAnnotations: {}
      extraLBService: false
      nodePort: null
      port: 7878
      type: ClusterIP
    volume: {}
  sabnzbd:
    container:
      image: docker.io/linuxserver/sabnzbd
      nodeSelector: {}
      port:
        http: 8080
        https: 9090
    enabled: true
    ingress:
      annotations: {}
      enabled: true
      path: /sabnzbd
      tls:
        enabled: false
        secretName: ""
    resources: {}
    service:
      http:
        extraLBAnnotations: {}
        extraLBService: false
        nodePort: null
        port: 8080
        type: ClusterIP
      https:
        extraLBAnnotations: {}
        extraLBService: false
        nodePort: null
        port: 9090
        type: ClusterIP
    volume: {}
  sonarr:
    container:
      image: docker.io/linuxserver/sonarr
      nodeSelector: {}
      port: 8989
    enabled: true
    ingress:
      annotations: {}
      enabled: true
      path: /sonarr
      tls:
        enabled: false
        secretName: ""
    resources: {}
    service:
      extraLBAnnotations: {}
      extraLBService: false
      nodePort: null
      port: 8989
      type: ClusterIP
    volume: {}
  transmission:
    config:
      auth:
        enabled: false
        password: ""
        username: ""
    container:
      image: docker.io/linuxserver/transmission
      nodeSelector: {}
      port:
        peer: 51413
        utp: 9091
    enabled: true
    ingress:
      annotations: {}
      enabled: true
      path: /transmission
      tls:
        enabled: false
        secretName: ""
    resources: {}
    service:
      peer:
        extraLBAnnotations: {}
        extraLBService: false
        nodePort: null
        nodePortUDP: null
        port: 51413
        type: ClusterIP
      utp:
        extraLBAnnotations: {}
        extraLBService: false
        nodePort: null
        port: 9091
        type: ClusterIP
    volume: {}


