{{ if .Values.jackett.enabled }}
---
### CONFIGMAPS
## INIT-CONTAINER
apiVersion: v1
data:
  ServerConfig.json: |
    {
      "BasePathOverride": "{{ .Values.jackett.ingress.path }}"
    }
  init-jackett.sh: |
    #!/bin/bash
    echo "### Initializing config ###"
    if [ ! -f /jackett-config/ServerConfig.json ]; then
      cp -n /init-jackett/ServerConfig.json /jackett-config/ServerConfig.json
      echo "### No configuration found, intialized with default settings ###"
    fi
kind: ConfigMap
metadata:
  name: init-jackett-cm
---
## APPLICATION
apiVersion: v1
kind: ConfigMap
metadata:
  name: jackett-config
data:
  PGID: "{{ .Values.general.pgid }}"
  PUID: "{{ .Values.general.puid }}"
---
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-mediaserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-mediaserver.selectorLabels" . | nindent 8 }}
        app: jackett
    spec:
      initContainers:
        - name: config-jackett
          image: docker.io/ubuntu:groovy
          command: ["/init-jackett/init-jackett.sh"]
          volumeMounts:
            - mountPath: /init-jackett
              name: init-files-jackett
          {{- if .Values.jackett.volume }}
            - name: {{ .Values.jackett.volume.name }}
              mountPath: /jackett-config
          {{- else }}
            - name: mediaserver-volume
              mountPath: /jackett-config
              subPath: "{{ .Values.general.storage.subPaths.config }}/jackett/Jackett"
          {{- end }}
          securityContext:
            runAsUser: {{ .Values.general.puid }}
            runAsGroup: {{ .Values.general.pgid }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: jackett-config
          image: "{{ .Values.jackett.container.image }}:{{ .Values.jackett.container.tag | default .Values.general.image_tag }}"
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: {{ .Values.jackett.container.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          ports:
            - name: jackett-port
              containerPort: {{ .Values.jackett.container.port }}
              protocol: TCP
          volumeMounts:
          {{- if .Values.jackett.volume }}
            - name: {{ .Values.jackett.volume.name }}
              mountPath: /config
          {{- else }}
            - name: mediaserver-volume
              mountPath: "/config"
              subPath: "{{ .Values.general.storage.subPaths.config }}/jackett"
          {{- end }}
          {{- with .Values.jackett.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if not .Values.general.storage.customVolume }}
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.general.storage.pvcName }}
        {{- else }}
        - name: mediaserver-volume
          {{- toYaml .Values.general.storage.volumes | nindent 10 }}
        {{- end }}
        {{- if .Values.jackett.volume }}
        - name: {{ .Values.jackett.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.jackett.volume.name }}
        {{- end }}
        - name: init-files-jackett
          configMap:
            defaultMode: 493
            name: init-jackett-cm
      {{- with merge .Values.jackett.container.nodeSelector .Values.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.general.podDistribution "cluster" }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
            weight: 100
      {{- else if eq .Values.general.podDistribution "spread" }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: "ScheduleAnyway"
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: {{ .Release.Name }}
      {{- end }}
---
### SERVICES
apiVersion: v1
kind: Service
metadata:
  name: jackett
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.jackett.service.type }}
  ports:
    - port: {{ .Values.jackett.service.port }}
      targetPort: {{ .Values.jackett.container.port }}
      protocol: TCP
{{ if eq .Values.jackett.service.type "NodePort" }}
      nodePort: {{ .Values.jackett.service.nodePort }}
{{ end }}
      name: jackett-port
  selector:
    app: jackett

---
{{ if .Values.jackett.service.extraLBService }}
apiVersion: v1
kind: Service
metadata:
  name: jackett-lb
  {{- with .Values.jackett.service.extraLBAnnotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.jackett.service.port }}
      targetPort: {{ .Values.jackett.container.port }}
      protocol: TCP
      name: jackett-port
  selector:
    app: jackett
{{ end }}
---

### INGRESS
{{ if .Values.jackett.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jackett
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
  {{- with .Values.jackett.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{ if .Values.jackett.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.general.ingress_host | quote }}
      secretName: {{ .Values.jackett.ingress.tls.secretName }}
{{ end }}
  ingressClassName: {{ .Values.general.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.general.ingress_host | quote }}
      http:
        paths:
          - path: {{ .Values.jackett.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: jackett
                port:
                  number: {{ .Values.jackett.service.port }}
{{ if .Values.general.ingress.enableSubdomains }}
    - host: {{ printf "%s.%s" "jackett" .Values.general.ingress_host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jackett
                port:
                  number: {{ .Values.jackett.service.port }}
{{ end }}
{{ end }}
{{ end }}
