container:
  image: docker.io/linuxserver/prowlarr
  tag: develop
  nodeSelector: {}
  port: 9696
service:
  type: ClusterIP
  port: 9696
  nodePort:
  extraLBService: false
  extraLBAnnotations: {}
ingress:
  enabled: true
  annotations: {}
  path: /prowlarr
  tls:
    enabled: false
    secretName: ""
resources: {}
volume: {}
