enabled: true
container:
  image: docker.io/linuxserver/jackett
  nodeSelector: {}
  port: 9117
service:
  type: ClusterIP
  port: 9117
  nodePort:
  extraLBService: false
  extraLBAnnotations: {}
  # Defines an additional LB service, requires cloud provider service or MetalLB
ingress:
  enabled: true
  annotations: {}
  path: /jackett
  tls:
    enabled: false
    secretName: ""
resources: {}
volume: {}
#  name: pvc-jackett-config
#  storageClassName: longhorn
#  annotations: {}
#  labels: {}
#  accessModes: ReadWriteOnce
#  storage: 5Gi
#  selector: {}
